[app]
name = "AyoLesCore"
version = "0.0.1"
host = "localhost"
port = 8080
read_timeout = 5
write_timeout = 10
idle_timeout = 15
temp = "template/*.gohtml"
files = "files"

[database]
host = "localhost"
port = 5432
name = "ayoles_db"
sslmode = "disable"
username = "postgres"
password = "123"
